FROM ruby:4.0.6-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential libpq-dev libjemalloc2 && \
    rm -rf /var/lib/apt/lists/*

# Use Jemalloc
ENV LD_PRELOAD=libjemalloc.so.2

ENV RUBY_YJIT_ENABLE=1
ENV RUBY_MN_THREADS=1
ENV RACK_ENV=production
# Negative values are fractions of CPU cores
ENV WORKERS=-1
ENV THREADS=1

WORKDIR /app

COPY Gemfile* .
RUN bundle config set deployment 'true'
RUN bundle install --jobs=$(nproc)

COPY . .

EXPOSE 8080

CMD ["ruby", "app.rb"]
